services:
  postgres:
    image: postgres
    container_name: uni-traffic-backend-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: uni-traffic-database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
